name: First Workflow
on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: step1
      run: echo "Step 1 complete"

    - name: step2
      run: echo "Step 2 complete"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Run Cowsays Action
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: "Ready for prodâ€“ship it!"
        color: magenta