name: First Workflow

on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1 Step 1
        run: echo "Step 1 complete!"
      - name: Echo Job 1 Step 2
        run: echo "Step 2 complete!"

  job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
      - name: Cowsays Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'Ready to ship!'
          color: 'magenta'
